In [1]:
import numpy as np

In [2]:
np.array([[2,4],
         [5,6,7]])

array([list([2, 4]), list([5, 6, 7])], dtype=object)

In [5]:
matrix = np.array([[2,4,3],
        [5,6,7]])

In [6]:
for row in matrix:
    for col in row:
        print(col)

2
4
3
5
6
7


In [7]:
matrix.sum()

27

In [8]:
matrix.mean()

4.5

In [9]:
matrix.max()

7

In [10]:
matrix + 10

array([[12, 14, 13],
       [15, 16, 17]])

In [11]:
matrix * 2

array([[ 4,  8,  6],
       [10, 12, 14]])

In [12]:
matrix * 2 + 10

array([[14, 18, 16],
       [20, 22, 24]])

In [13]:
mylist = [1,5,'hello']

In [17]:
mylist + 7

14

In [18]:
matrix.T

array([[2, 5],
       [4, 6],
       [3, 7]])

In [19]:
matrix.T

array([[2, 5],
       [4, 6],
       [3, 7]])

In [20]:
matrix.shape

(2, 3)

In [21]:
matrix3 = np.array([[0,0,0],[10,10,10]])

In [22]:
matrix3

array([[ 0,  0,  0],
       [10, 10, 10]])

In [23]:
matrix * matrix3

array([[ 0,  0,  0],
       [50, 60, 70]])

In [ ]:
matrix2 = np.